# Generated by Django 5.1.1 on 2025-07-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_appointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assigned_doctor_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
