# Generated by Django 5.1.1 on 2025-07-17 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0003_remove_patient_assigned_doctor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assigned_doctor_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor'),
        ),
    ]
