# Generated by Django 5.1.1 on 2025-07-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_patient_assigned_doctor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='date_of_birth',
            new_name='dateofbirth',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='phone_number',
            new_name='mobilenumber',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
    ]
