# Generated by Django 5.1.1 on 2025-07-18 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_rename_date_of_birth_patient_dateofbirth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='dateofbirth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='username',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='mobilenumber',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
