# Generated by Django 5.1.1 on 2025-07-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_rename_dateofbirth_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='date_of_birth',
            new_name='dateofbirth',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='phone_number',
            new_name='mobilenumber',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='1234', max_length=20),
        ),
    ]
